name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Tests and Coverage
        run: npm run test
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          PORT: ${{secrets.PORT}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRATION_TIME: ${{secrets.JWT_EXPIRATION_TIME}}
          NODE_ENV: ${{secrets.NODE_ENV}}
      - name: Build-ts
        run: npm run build
      - name: Sonar Cloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

  build-and-push-docker:
    name: Build and push Docker image
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vonnwatson/social-backend
      IMAGE_TAG: build-${{github.run_number}}
    if: github.ref=='refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker Build image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -f docker/production/Dockerfile .
      - name: Docker Push image
        run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
